enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1  # $(nproc)

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
included-patches = "'Permanent repeat'"

[Twitter]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"
excluded-patches = "'Dynamic color' 'Hide recommended users'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
excluded-patches = "'Alternative thumbnails'"
patcher-args = "-e 'Custom branding' -OappName=Youtube!"

[Twitch!]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
included-patches = "'Debug mode'"
arch = "both"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "auto"

[InShorts]
enabled = true
version = "auto"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
arch = "arm64-v8a"
